server:
  port: 8081

#配置数据源的属性
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.186.92/ruihuadf?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: f763aa86e9c7de2a
    druid:
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

logging:
  level:
    root: warn
    com.xinggevip.dao: trace  # 比debug信息更详细
  pattern:
    console: '%p%m%n'


mybatis-plus:
  configuration:
    call-setters-on-nulls: true # 如果sql查询的字段为null，也把结果返回到map中
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      field-strategy: not_null #not_null 为null则不加入条件; not_empty 非空判断（null和空值） true则不加入条件; ignored 为忽略判断，不管是否为null或为空，一律覆盖，有风险
#      table-prefix: t_ #表前缀
#      id-type: auto
  #configLocation:classpath:mybatis-config.xml # configLocation不能和configuration同时设置，否则会报错
#  type-aliases-package: com.xinggevip.domain  # 设置包名 这样mapper.xml文件就不用写全路径的包名了
